
package customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "windService", targetNamespace = "http://futureweather/windspeed/message", wsdlLocation = "file:/Volumes/Transcend/School/IAC/opdrachten/praktijkopdracht1/XML/windService.wsdl")
public class WindService
    extends Service
{

    private final static URL WINDSERVICE_WSDL_LOCATION;
    private final static WebServiceException WINDSERVICE_EXCEPTION;
    private final static QName WINDSERVICE_QNAME = new QName("http://futureweather/windspeed/message", "windService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Volumes/Transcend/School/IAC/opdrachten/praktijkopdracht1/XML/windService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WINDSERVICE_WSDL_LOCATION = url;
        WINDSERVICE_EXCEPTION = e;
    }

    public WindService() {
        super(__getWsdlLocation(), WINDSERVICE_QNAME);
    }

    public WindService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WINDSERVICE_QNAME, features);
    }

    public WindService(URL wsdlLocation) {
        super(wsdlLocation, WINDSERVICE_QNAME);
    }

    public WindService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WINDSERVICE_QNAME, features);
    }

    public WindService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WindService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort() {
        return super.getPort(new QName("http://futureweather/windspeed/message", "WS-Port"), WSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://futureweather/windspeed/message", "WS-Port"), WSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WINDSERVICE_EXCEPTION!= null) {
            throw WINDSERVICE_EXCEPTION;
        }
        return WINDSERVICE_WSDL_LOCATION;
    }

}
