
package customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS-Interface", targetNamespace = "http://futureweather/windspeed/message")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param request
     * @return
     *     returns customer.Response
     * @throws Fault_Exception
     */
    @WebMethod
    @WebResult(name = "windspeedresponse", targetNamespace = "http://futureweather/windspeed/response", partName = "response")
    public Response getWindSpeed(
        @WebParam(name = "windspeedrequest", targetNamespace = "http://futureweather/windspeed/request", partName = "request")
        Request request)
        throws Fault_Exception
    ;

}
